[REL-261] ViewStore initializer for void state
thebrowsercompany/swift-composable-architecture pull request #14
Opened 2022-06-28 23:17 UTC by amonshiz

A `ViewStore` that is created from a `Store` with `State == Void` gains little to nothing by subscribing to updates on 
the parent `Store`'s state. Further, in our fork that adds the `removeDuplicates` checks we defaulted to the `==` 
function which will always return `true` for `Void` values, meaning that the updates never made it to the `ViewStore`'s
state and so subscribers (if there were any) would never be updated either.

Within `browser-swift` we currently use the `ViewStore(store.stateless)` pattern exclusively for sending actions back 
into parent stores. This is great and the expected usage but currently we pay for these view stores on the scoping pass
when they are never going to update and have no subscribers. By removing their subscription to their parent store they 
will not take part in anything other than passing sent actions.

2022-06-28 23:18 UTC, amonshiz commented on Sources/ComposableArchitecture/ViewStore.swift
> -    self.init(store, removeDuplicates: ==, instrumentation: instrumentation, file: file, line: line)
By always using this `==` we were essentially doing the same but still paying for the cost of scoping down and then checking the equality. Now we will just not even have to scope or compare.

2022-06-29 08:22 UTC, krzysztofzablocki requested changes

2022-06-29 08:22 UTC, krzysztofzablocki commented on Sources/ComposableArchitecture/ViewStore.swift
> +    self._state = CurrentValueRelay(())
missing `instrumentation.viewStoreCreated?(self as AnyObject, file, line)`

2022-06-29 11:12 UTC, krzysztofzablocki approved these changes
pending that missing tracking

2022-06-29 11:12 UTC, diederich approved these changes
Thanks for trying this! LGTM % @krzysztofzablocki 's comment!
Did you get any numbers from this?

2022-06-29 14:40 UTC, amonshiz reviewed
> Did you get any numbers from this?

@diederich no I have not yet looked into before and after. Was end of my day when I submitted this so will try to find time today :)

2022-06-29 14:40 UTC, amonshiz commented on Sources/ComposableArchitecture/ViewStore.swift
> +    self._state = CurrentValueRelay(())
Doh! Will do!

2022-06-29 14:41 UTC, amonshiz reviewed
But @diederich I do at least have tests that verify that there were no `ViewStore` deduplication and state change callbacks made :)

2022-06-29 14:57 UTC, merged